# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python


## The release build overwrites these trigger in Azure
trigger:
  branches:
    include:
      - master
      - 'refs/tags/*'
    exclude:
      - next_*
pr:
  - master

jobs:
  
- job: 'Package'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
      displayName: 'Install dependencies'
    - script: |
        python setup.py sdist
      displayName: 'Make sdist'
    - script: |
        python setup.py bdist_wheel --universal
      displayName: 'Make wheel'
    - script: |
        pip install pytest pytest-azurepipelines
        pip install .
        pytest
      displayName: 'pytest'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'artifact'
        targetPath: 'dist'